/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2016-11-30 15:15:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.lang.String;
import java.sql.ResultSet;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>我存我惠查询</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/admin.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/login.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"login\">\r\n");
      out.write(" ");

 String username= request.getParameter("username");
 //out.println(username);
 String money= request.getParameter("money");
 String name= request.getParameter("name");
  //System.out.println(username); 

   try{
	   Class.forName("oracle.jdbc.driver.OracleDriver");
	   
   }catch(ClassNotFoundException e){
	   
	   e.printStackTrace();
   }

   try{
       //Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
       Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","hankangqi");
       /*if(con==null){
          System.out.println("与oracle数据库连接失败！");
      }else{
           System.out.println("与oracle数据库连接成功！");
      }*/
       Statement stmt = con.createStatement();
       String sql = "select * from hkm where username='"+username+"'";
       //System.out.println(username);
       ResultSet rs = stmt.executeQuery(sql);
       //System.out.println("不错");
       if(rs.next()){
    	 // System.out.println("fdsfdf");
    	 
    	 //System.out.println(mo);
    	   if(rs.getInt("money")>0&rs.getInt("money")<100000){
        	  // System.out.println("不错");
               //response.sendRedirect("admin.jsp");
    		  
      out.write("\r\n");
      out.write("    \t    \t <div >\r\n");
      out.write("    \t    \t <table border=\"1\">\r\n");
      out.write("    \t    \t <tr class=\"biao\">\r\n");
      out.write("    \t         <tr><td>尊敬的");
      out.print(rs.getString("name") );
      out.write("，您的大驾光临让我们蓬荜生辉，您的余额为:");
      out.print(rs.getInt("money"));
      out.write("请努力存钱哦</td></tr>\r\n");
      out.write("    \t         <tr><td>姓名：");
      out.print(rs.getString("name") );
      out.write("</td></tr>\r\n");
      out.write("    \t         <tr><td>账号：");
      out.print(rs.getString("username") );
      out.write("</td></tr>\r\n");
      out.write("    \t         <tr><td>余额：");
      out.print(rs.getInt("money") );
      out.write("</td>\r\n");
      out.write("    \t         </tr>\r\n");
      out.write("    \t         </table>\r\n");
      out.write("    \t         <input type=\"button\" name=\"mit\" value=\"返回首页\" onclick=\"javascript:window.history.back(-1);\">\r\n");
      out.write("    \t    \t </div>\r\n");
      out.write("    \t    \t ");

           }if(rs.getInt("money")<=0){
        	   
      out.write("\r\n");
      out.write("          \t <div >\r\n");
      out.write("          \t <table border=\"2\">\r\n");
      out.write("          \t <tr class=\"biao2\">\r\n");
      out.write("               <td>尊敬的");
      out.print(rs.getString("name") );
      out.write("，您的余额:");
      out.print(rs.getInt("money"));
      out.write("请努力挣钱哦，我们知道您的地址，请您尽快还钱</td></tr>\r\n");
      out.write("              \r\n");
      out.write("               </table>\r\n");
      out.write("               <input type=\"button\" name=\"Sub\" value=\"返回首页\" onclick=\"javascript:window.history.back(-1);\">\r\n");
      out.write("          \t </div>\r\n");
      out.write("          \t ");

           }
      
          else if(rs.getInt("money")>=100000){
    	   //System.out.println("不对啊！");
    	   //response.sendRedirect("VIP.jsp");
    	   
      out.write("\r\n");
      out.write("    \t   <div >\r\n");
      out.write("    \t   <table border=\"2\">\r\n");
      out.write("    \t  <tr class=\"biao3\"> <td>尊敬的");
      out.print(rs.getString("name") );
      out.write("，作为我们尊敬的vip用户，我们非常荣幸为您服务，希望您能感受到我们的热情\r\n");
      out.write("    \t  希望我们的服务使您感觉到了温暖与幸福，希望您继续光临我们的银行，我们将为您提供最优质的服务\r\n");
      out.write("    \t\r\n");
      out.write("    \t  </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    <input type=\"button\" name=\"mit\" value=\"返回首页\" onclick=\"javascript:window.history.back(-1);\">\r\n");
      out.write("    </div>\r\n");
      out.write("      ");
 
      }
       }
   }catch (Exception e) {
       e.printStackTrace();
   }
 


      out.write(" \r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
